---
".gitlab-ci.yml":
  delete: true
".travis.yml":
  simplecov: true
appveyor.yml:
  simplecov: true
Gemfile:
  required:
    ":system_tests":
    - gem: puppet-module-posix-system-r#{minor_version}
      platforms: ruby
    - gem: puppet-module-win-system-r#{minor_version}
      platforms:
      - mswin
      - mingw
      - x64_mingw
    - gem: puppet-blacksmith
      version: "~> 3.4"
    - gem: beaker-testmode_switcher
      version: "~> 0.4"
    - gem: master_manipulator
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
