---
".gitlab-ci.yml":
  delete: true
".travis.yml":
  deploy_to_forge:
    enabled: false
  simplecov: true
appveyor.yml:
  simplecov: true
Gemfile:
  required:
    ":system_tests":
    - gem: puppet-module-posix-system-r#{minor_version}
      platforms: ruby
    - gem: puppet-module-win-system-r#{minor_version}
      platforms:
      - mswin
      - mingw
      - x64_mingw
    - gem: puppet-blacksmith
      version: "~> 3.4"
    - gem: beaker-testmode_switcher
      version: "~> 0.4"
    - gem: master_manipulator
  optional:
    ':development':
    - gem: 'github_changelog_generator'
      git: 'https://github.com/skywinder/github-changelog-generator'
      ref: '20ee04ba1234e9e83eb2ffb5056e23d641c7a018'
      condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.2.2')"  
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
