---
Gemfile:
  optional:
    ':development':
      - gem: 'rspec-puppet'
        platforms: ["mswin", "mingw", "x64_mingw"]
        version: '< 2.6.0'
Rakefile:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true
.gitignore:
  paths:
  - 'bin'
  - 'import'
  - '.tmp'
  - '.rbenv-gemsets'
  - '.ruby-version'
  - '*.lock'
  - 'vendor/'
appveyor.yml:
  appveyor_bundle_install: "bundle install --jobs 4 --retry 2 --without system_tests build"
  matrix_extras:
    - PUPPET_GEM_VERSION: 4.2.3
      RUBY_VER: 21-x64
  test_script:
    - 'bundle exec rspec spec/unit spec/integration -fd -b'
MAINTAINERS.md:
  maintainers:
    - "Puppet Windows Team `windows |at| puppet |dot| com`"
NOTICE:
  copyright_holders:
    - name: 'Puppet, Inc.'
      begin: 2015
    - name: 'Marc Sutter, original author'
      begin: 2014
      end: 2015
